import {
  Activity,
  Paperclip,
  Wifi,
  WifiOff,
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Calendar,
  Clock,
  Download,
  Gift,
  Palmtree,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  Calculator,
  Check,
  ClipboardList,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleDollarSign,
  DollarSign,
  Ellipsis,
  FileSpreadsheet,
  FileText,
  Folder,
  GitBranch,
  HandCoins,
  Headphones,
  Landmark,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  ListTree,
  Lock,
  MessageCircle,
  MessageSquare,
  Moon,
  Package,
  PackageCheck,
  Plus,
  Receipt,
  Repeat,
  Router,
  RotateCw,
  RefreshCw,
  Link2,
  Signal,
  RadioTower,
  Scale,
  ScrollText,
  Inbox,
  Search,
  Send,
  Settings,
  ShoppingCart,
  Smile,
  Sparkles,
  Sun,
  Target,
  TrendingUp,
  TrendingDown,
  Truck,
  User,
  UserCheck,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
  X,
  Zap,
  CornerDownLeft,
  FilePlus,
  Keyboard,
  LogOut,
  Shield,
  ShieldCheck,
  Eye,
  EyeOff,
  Loader2,
  KeyRound,
  UserCog,
  ShieldAlert,
  HardHat,
  Stethoscope,
  GraduationCap,
  AlertTriangle,
  ClipboardCheck,
  ListChecks,
  FireExtinguisher,
  UsersRound,
  Siren,
  Contact,
  Hourglass,
  PackageX,
  SlidersHorizontal,
  PanelLeft,
  PanelLeftClose,
  Menu,
  Wrench,
  History,
  Gauge,
  Phone,
  Mail,
  Briefcase,
  MapPin,
  SquarePen,
  FileSignature,
  CalendarPlus,
  CalendarClock,
  WandSparkles,
  Palette,
  Image as ImageIcon,
  Upload,
  Camera,
  Trash2,
  Pause,
  Play,
  List,
  Copy,
  Cake,
  Navigation,
  Cloud,
  ExternalLink,
  Flag,
  Save,
  ToggleLeft,
  ToggleRight,
  Power,
  Tv,
  Network,
  Ban,
  Info,
  FlaskConical,
  type LucideIcon,
} from "lucide-react";

const registry: Record<string, LucideIcon> = {
  tv: Tv,
  flag: Flag,
  save: Save,
  "toggle-left": ToggleLeft,
  "toggle-right": ToggleRight,
  power: Power,
  activity: Activity,
  wifi: Wifi,
  "wifi-off": WifiOff,
  image: ImageIcon,
  upload: Upload,
  camera: Camera,
  trash: Trash2,
  "alert-circle": AlertCircle,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  calendar: Calendar,
  clock: Clock,
  download: Download,
  gift: Gift,
  palmtree: Palmtree,
  banknote: Banknote,
  "bar-chart-3": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  boxes: Boxes,
  calculator: Calculator,
  check: Check,
  "clipboard-list": ClipboardList,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-up-down": ChevronsUpDown,
  "circle-dollar-sign": CircleDollarSign,
  "dollar-sign": DollarSign,
  ellipsis: Ellipsis,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  folder: Folder,
  "git-branch": GitBranch,
  "hand-coins": HandCoins,
  headphones: Headphones,
  landmark: Landmark,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "life-buoy": LifeBuoy,
  "list-tree": ListTree,
  lock: Lock,
  paperclip: Paperclip,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  moon: Moon,
  package: Package,
  "package-check": PackageCheck,
  plus: Plus,
  receipt: Receipt,
  router: Router,
  "rotate-cw": RotateCw,
  "refresh-cw": RefreshCw,
  link: Link2,
  signal: Signal,
  "radio-tower": RadioTower,
  repeat: Repeat,
  scale: Scale,
  "scroll-text": ScrollText,
  search: Search,
  inbox: Inbox,
  send: Send,
  settings: Settings,
  "shopping-cart": ShoppingCart,
  smile: Smile,
  sparkles: Sparkles,
  sun: Sun,
  target: Target,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  truck: Truck,
  user: User,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  users: Users,
  wallet: Wallet,
  warehouse: Warehouse,
  x: X,
  zap: Zap,
  info: Info,
  "flask-conical": FlaskConical,
  "corner-down-left": CornerDownLeft,
  "file-plus": FilePlus,
  keyboard: Keyboard,
  "log-out": LogOut,
  shield: Shield,
  "shield-check": ShieldCheck,
  eye: Eye,
  "eye-off": EyeOff,
  loader: Loader2,
  "key-round": KeyRound,
  "user-cog": UserCog,
  "shield-alert": ShieldAlert,
  "hard-hat": HardHat,
  stethoscope: Stethoscope,
  "graduation-cap": GraduationCap,
  "alert-triangle": AlertTriangle,
  "clipboard-check": ClipboardCheck,
  "list-checks": ListChecks,
  "fire-extinguisher": FireExtinguisher,
  "users-round": UsersRound,
  siren: Siren,
  contact: Contact,
  hourglass: Hourglass,
  "package-x": PackageX,
  "sliders-horizontal": SlidersHorizontal,
  "panel-left": PanelLeft,
  "panel-left-close": PanelLeftClose,
  menu: Menu,
  wrench: Wrench,
  history: History,
  gauge: Gauge,
  phone: Phone,
  mail: Mail,
  briefcase: Briefcase,
  "map-pin": MapPin,
  pencil: SquarePen,
  "file-signature": FileSignature,
  "calendar-plus": CalendarPlus,
  "calendar-clock": CalendarClock,
  "wand-sparkles": WandSparkles,
  palette: Palette,
  pause: Pause,
  play: Play,
  list: List,
  copy: Copy,
  cake: Cake,
  navigation: Navigation,
  cloud: Cloud,
  "external-link": ExternalLink,
  network: Network,
  ban: Ban,
};

export function Icon({
  name,
  size = 16,
  className,
  strokeWidth = 2,
}: {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = registry[name] ?? Sparkles;
  return <Cmp size={size} className={className} strokeWidth={strokeWidth} />;
}
